#!/usr/bin/env python3
"""
GLM + STI Ingest Service — MWN
===============================
Polls NOAA GOES-East GLM-L2-LCFA files from AWS S3 for lightning clusters,
AND polls NEXRAD Level III STI (Product 58) files from AWS S3 for
storm cell identification and tracking (SCIT) data.

Endpoints:
    /glm        — GeoJSON lightning flash clusters
    /status     — GLM service health
    /sti        — GeoJSON NEXRAD storm cells CONUS-wide (or filtered by bounds)
    /sti/status — STI service health

Requirements
------------
    pip install boto3 xarray netCDF4 scipy flask flask-cors

NEXRAD Level III STI Notes
--------------------------
- Product 58 (STI) contains storm cell positions and motion vectors
- Generated by the WSR-88D SCIT algorithm every volume scan (~4-6 min)
- Available in real-time on AWS S3: s3://unidata-nexrad-level3/
- File format: {SITE}_STI_{YYYY}_{MM}_{DD}_{HH}_{MM}_{SS}
- Binary format parsed using struct (ICD 2620001)
"""

import os
import io
import json
import time
import math
import struct
import logging
import threading
from datetime import datetime, timezone, timedelta
from collections import defaultdict

import boto3
import xarray as xr
import numpy as np
from flask import Flask, jsonify, request
from flask_cors import CORS
from botocore import UNSIGNED
from botocore.config import Config

# ── CONFIG ────────────────────────────────────────────────────────────────────

PORT           = int(os.environ.get("PORT", 8801))
POLL_INTERVAL  = 20          # seconds between GLM S3 polls
CLUSTER_RADIUS = 0.5         # degrees — flash clustering radius
MIN_FLASHES    = 1           # minimum flashes to report a cluster
MAX_AGE_SEC    = 60          # discard GLM files older than this
CONUS_BOUNDS   = dict(lat_min=24.0, lat_max=50.0, lon_min=-125.0, lon_max=-66.0)

# Satellite buckets in priority order (GOES-East first)
GOES_BUCKETS = ['noaa-goes19', 'noaa-goes16']
GLM_PREFIX   = 'GLM-L2-LCFA'

# STI config
STI_BUCKET       = 'unidata-nexrad-level3'
STI_POLL_INTERVAL = 120       # seconds between STI polls
STI_MAX_AGE_SEC  = 600        # discard STI cells older than 10 min
STI_BATCH_SIZE   = 20         # concurrent S3 requests per batch

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger('mwn-ingest')

# ── NEXRAD SITE LIST ──────────────────────────────────────────────────────────

NEXRAD_SITES = [
    {'id':'KABR','lat':45.456,'lon':-98.413},{'id':'KABX','lat':35.150,'lon':-106.824},
    {'id':'KAKQ','lat':36.984,'lon':-77.008},{'id':'KAMA','lat':35.233,'lon':-101.709},
    {'id':'KAMX','lat':25.611,'lon':-80.413},{'id':'KAPX','lat':44.907,'lon':-84.720},
    {'id':'KARX','lat':43.823,'lon':-91.191},{'id':'KATX','lat':48.195,'lon':-122.496},
    {'id':'KBBX','lat':39.496,'lon':-121.632},{'id':'KBGM','lat':42.200,'lon':-75.985},
    {'id':'KBHX','lat':40.499,'lon':-124.292},{'id':'KBIS','lat':46.771,'lon':-100.760},
    {'id':'KBLX','lat':45.854,'lon':-108.607},{'id':'KBMX','lat':33.172,'lon':-86.770},
    {'id':'KBOX','lat':41.956,'lon':-71.137},{'id':'KBRO','lat':25.916,'lon':-97.419},
    {'id':'KBUF','lat':42.949,'lon':-78.737},{'id':'KBYX','lat':24.598,'lon':-81.703},
    {'id':'KCAE','lat':33.949,'lon':-81.118},{'id':'KCBW','lat':46.039,'lon':-67.806},
    {'id':'KCBX','lat':43.491,'lon':-116.236},{'id':'KCCX','lat':40.923,'lon':-78.004},
    {'id':'KCLE','lat':41.413,'lon':-81.860},{'id':'KCLX','lat':32.656,'lon':-81.042},
    {'id':'KCRP','lat':27.784,'lon':-97.511},{'id':'KCXX','lat':44.511,'lon':-73.167},
    {'id':'KCYS','lat':41.152,'lon':-104.806},{'id':'KDAX','lat':38.501,'lon':-121.678},
    {'id':'KDDC','lat':37.761,'lon':-99.969},{'id':'KDFX','lat':29.273,'lon':-100.281},
    {'id':'KDGX','lat':32.280,'lon':-89.984},{'id':'KDIX','lat':39.947,'lon':-74.411},
    {'id':'KDLH','lat':46.837,'lon':-92.210},{'id':'KDMX','lat':41.731,'lon':-93.723},
    {'id':'KDOX','lat':38.826,'lon':-75.440},{'id':'KDTX','lat':42.700,'lon':-83.472},
    {'id':'KDVN','lat':41.612,'lon':-90.581},{'id':'KDYX','lat':32.538,'lon':-99.254},
    {'id':'KEAX','lat':38.810,'lon':-94.264},{'id':'KEMX','lat':31.894,'lon':-110.630},
    {'id':'KENX','lat':42.586,'lon':-74.064},{'id':'KEOX','lat':31.460,'lon':-85.459},
    {'id':'KEPZ','lat':31.873,'lon':-106.698},{'id':'KESX','lat':35.701,'lon':-114.891},
    {'id':'KEVX','lat':30.565,'lon':-85.922},{'id':'KEWX','lat':29.704,'lon':-98.029},
    {'id':'KEYX','lat':35.098,'lon':-117.561},{'id':'KFCX','lat':37.024,'lon':-80.274},
    {'id':'KFDR','lat':34.362,'lon':-98.976},{'id':'KFDX','lat':34.635,'lon':-103.630},
    {'id':'KFFC','lat':33.364,'lon':-84.566},{'id':'KFSD','lat':43.588,'lon':-96.729},
    {'id':'KFSX','lat':34.574,'lon':-111.198},{'id':'KFTG','lat':39.787,'lon':-104.546},
    {'id':'KFWS','lat':32.573,'lon':-97.303},{'id':'KGGW','lat':48.206,'lon':-106.625},
    {'id':'KGJX','lat':39.062,'lon':-108.214},{'id':'KGLD','lat':39.367,'lon':-101.700},
    {'id':'KGRB','lat':44.499,'lon':-88.111},{'id':'KGRK','lat':30.722,'lon':-97.383},
    {'id':'KGRR','lat':42.894,'lon':-85.545},{'id':'KGSP','lat':34.883,'lon':-82.220},
    {'id':'KGWX','lat':33.897,'lon':-88.329},{'id':'KGYX','lat':43.891,'lon':-70.257},
    {'id':'KHDX','lat':33.077,'lon':-106.123},{'id':'KHGX','lat':29.472,'lon':-95.079},
    {'id':'KHNX','lat':36.314,'lon':-119.632},{'id':'KHPX','lat':36.737,'lon':-87.285},
    {'id':'KHTX','lat':34.931,'lon':-86.083},{'id':'KICT','lat':37.655,'lon':-97.443},
    {'id':'KICX','lat':37.591,'lon':-112.862},{'id':'KILN','lat':39.420,'lon':-83.822},
    {'id':'KILX','lat':40.151,'lon':-89.337},{'id':'KIND','lat':39.708,'lon':-86.280},
    {'id':'KINX','lat':36.175,'lon':-95.565},{'id':'KIWA','lat':33.289,'lon':-111.670},
    {'id':'KIWX','lat':41.359,'lon':-85.700},{'id':'KJAX','lat':30.485,'lon':-81.702},
    {'id':'KJGX','lat':32.675,'lon':-83.351},{'id':'KJKL','lat':37.591,'lon':-83.313},
    {'id':'KLBB','lat':33.654,'lon':-101.814},{'id':'KLCH','lat':30.125,'lon':-93.216},
    {'id':'KLIX','lat':30.337,'lon':-89.826},{'id':'KLNX','lat':41.958,'lon':-100.576},
    {'id':'KLOT','lat':41.604,'lon':-88.085},{'id':'KLRX','lat':40.740,'lon':-116.803},
    {'id':'KLSX','lat':38.699,'lon':-90.683},{'id':'KLTX','lat':33.989,'lon':-78.429},
    {'id':'KLVX','lat':37.975,'lon':-85.944},{'id':'KLWX','lat':38.975,'lon':-77.478},
    {'id':'KLZK','lat':34.836,'lon':-92.262},{'id':'KMAF','lat':31.943,'lon':-102.189},
    {'id':'KMAX','lat':42.081,'lon':-122.717},{'id':'KMBX','lat':48.393,'lon':-100.864},
    {'id':'KMHX','lat':34.776,'lon':-76.876},{'id':'KMKX','lat':42.968,'lon':-88.551},
    {'id':'KMLB','lat':28.113,'lon':-80.654},{'id':'KMOB','lat':30.679,'lon':-88.240},
    {'id':'KMPX','lat':44.849,'lon':-93.566},{'id':'KMQT','lat':46.531,'lon':-87.548},
    {'id':'KMRX','lat':36.169,'lon':-83.402},{'id':'KMSX','lat':47.041,'lon':-113.986},
    {'id':'KMTX','lat':41.263,'lon':-112.448},{'id':'KMUX','lat':37.155,'lon':-121.898},
    {'id':'KMVX','lat':47.528,'lon':-97.326},{'id':'KMXX','lat':32.537,'lon':-85.790},
    {'id':'KNKX','lat':32.919,'lon':-117.042},{'id':'KNQA','lat':35.345,'lon':-89.873},
    {'id':'KOAX','lat':41.320,'lon':-96.367},{'id':'KOHX','lat':36.247,'lon':-86.563},
    {'id':'KOKX','lat':40.866,'lon':-72.864},{'id':'KOTX','lat':47.681,'lon':-117.627},
    {'id':'KOUN','lat':35.236,'lon':-97.462},{'id':'KPAH','lat':37.068,'lon':-88.772},
    {'id':'KPBZ','lat':40.532,'lon':-80.218},{'id':'KPDT','lat':45.691,'lon':-118.853},
    {'id':'KPOE','lat':31.156,'lon':-92.976},{'id':'KPUX','lat':38.460,'lon':-104.181},
    {'id':'KRAX','lat':35.665,'lon':-78.490},{'id':'KRGX','lat':39.754,'lon':-119.462},
    {'id':'KRIW','lat':43.066,'lon':-108.477},{'id':'KRLX','lat':38.311,'lon':-81.723},
    {'id':'KRMX','lat':41.407,'lon':-79.158},{'id':'KRNK','lat':37.207,'lon':-80.410},
    {'id':'KRTX','lat':45.715,'lon':-122.966},{'id':'KSFX','lat':43.106,'lon':-112.686},
    {'id':'KSGF','lat':37.235,'lon':-93.400},{'id':'KSHV','lat':32.451,'lon':-93.841},
    {'id':'KSJT','lat':31.371,'lon':-100.493},{'id':'KSOX','lat':33.818,'lon':-117.636},
    {'id':'KSRX','lat':35.290,'lon':-94.362},{'id':'KTBW','lat':27.706,'lon':-82.402},
    {'id':'KTFX','lat':47.460,'lon':-111.385},{'id':'KTLH','lat':30.398,'lon':-84.329},
    {'id':'KTLX','lat':35.333,'lon':-97.278},{'id':'KTWX','lat':38.997,'lon':-96.233},
    {'id':'KTYX','lat':43.756,'lon':-75.680},{'id':'KUDX','lat':44.125,'lon':-102.830},
    {'id':'KUEX','lat':40.321,'lon':-98.442},{'id':'KVAX','lat':30.890,'lon':-83.002},
    {'id':'KVBX','lat':34.838,'lon':-120.398},{'id':'KVNX','lat':36.741,'lon':-98.128},
    {'id':'KVTX','lat':34.412,'lon':-119.179},{'id':'KVWX','lat':38.260,'lon':-87.725},
    {'id':'KYUX','lat':32.495,'lon':-114.657},{'id':'KLGX','lat':47.117,'lon':-124.107},
]

NEXRAD_SITE_MAP = {s['id']: s for s in NEXRAD_SITES}

# ── GLOBAL STATE ──────────────────────────────────────────────────────────────

_state = {
    'clusters':    [],
    'file_time':   None,
    'fetch_time':  None,
    'source':      None,
    'file_count':  0,
    'flash_count': 0,
    'error':       None,
}

_sti_state = {
    'cells':          [],      # list of storm cell dicts
    'last_poll':      None,
    'poll_count':     0,
    'error_count':    0,
    'sites_checked':  0,
    'sites_with_data': 0,
    'last_file_by_site': {},   # site_id → last processed key
}

_lock = threading.Lock()
_sti_lock = threading.Lock()

# ── S3 CLIENT (unsigned — public bucket) ──────────────────────────────────────

s3 = boto3.client('s3', config=Config(signature_version=UNSIGNED), region_name='us-east-1')


# ═══════════════════════════════════════════════════════════════════════════════
# GLM PARSING (unchanged from original)
# ═══════════════════════════════════════════════════════════════════════════════

def latest_glm_key(bucket: str, dt: datetime) -> str | None:
    keys = []
    for offset_h in (0, 1):
        t = dt - timedelta(hours=offset_h)
        prefix = f"{GLM_PREFIX}/{t.year}/{t.timetuple().tm_yday:03d}/{t.hour:02d}/"
        try:
            resp = s3.list_objects_v2(Bucket=bucket, Prefix=prefix)
            for obj in resp.get('Contents', []):
                keys.append((obj['LastModified'], obj['Key']))
        except Exception as e:
            log.debug(f"list {bucket}/{prefix}: {e}")
    if not keys:
        return None
    keys.sort(key=lambda x: x[0], reverse=True)
    return keys[0][1]


def parse_glm_file(bucket: str, key: str) -> list[dict]:
    import tempfile
    log.info(f"Fetching s3://{bucket}/{key}")
    obj = s3.get_object(Bucket=bucket, Key=key)
    data = obj['Body'].read()
    with tempfile.NamedTemporaryFile(suffix='.nc', delete=False) as tmp:
        tmp.write(data)
        tmp_path = tmp.name
    try:
        ds = xr.open_dataset(tmp_path, engine='netcdf4')
        lats    = ds['flash_lat'].values.astype(float)
        lons    = ds['flash_lon'].values.astype(float)
        energy  = ds['flash_energy'].values.astype(float)
        area    = ds['flash_area'].values.astype(float)
        ds.close()
    finally:
        os.unlink(tmp_path)
    flashes = []
    b = CONUS_BOUNDS
    for i in range(len(lats)):
        la, lo = lats[i], lons[i]
        if math.isnan(la) or math.isnan(lo):
            continue
        if not (b['lat_min'] <= la <= b['lat_max'] and b['lon_min'] <= lo <= b['lon_max']):
            continue
        flashes.append({
            'lat': round(float(la), 4), 'lon': round(float(lo), 4),
            'energy': float(energy[i]) if not math.isnan(energy[i]) else 0.0,
            'area': float(area[i]) if not math.isnan(area[i]) else 0.0,
        })
    log.info(f"  → {len(flashes)} CONUS flashes from {len(lats)} total")
    return flashes


def cluster_flashes(flashes: list[dict]) -> list[dict]:
    if not flashes:
        return []
    assigned = [False] * len(flashes)
    clusters = []
    for i, f in enumerate(flashes):
        if assigned[i]:
            continue
        members = [f]
        assigned[i] = True
        for j in range(i + 1, len(flashes)):
            if assigned[j]:
                continue
            g = flashes[j]
            if abs(f['lat'] - g['lat']) > CLUSTER_RADIUS * 2:
                continue
            dist = math.hypot(f['lat'] - g['lat'], f['lon'] - g['lon'])
            if dist <= CLUSTER_RADIUS:
                members.append(g)
                assigned[j] = True
        if len(members) < MIN_FLASHES:
            continue
        c_lat = sum(m['lat'] for m in members) / len(members)
        c_lon = sum(m['lon'] for m in members) / len(members)
        t_nrg = sum(m['energy'] for m in members)
        t_area = sum(m['area'] for m in members)
        clusters.append({
            'lat': round(c_lat, 4), 'lon': round(c_lon, 4),
            'count': len(members),
            'area': round(max(t_area / 1e3, 0.01), 4),
            'total_energy': round(t_nrg, 2),
        })
    clusters.sort(key=lambda c: c['count'], reverse=True)
    return clusters


# ═══════════════════════════════════════════════════════════════════════════════
# STI PARSING — NEXRAD Level III Product 58 (Storm Tracking Information)
# ═══════════════════════════════════════════════════════════════════════════════

def get_latest_sti_key(site_id: str) -> str | None:
    """Find the most recent STI file for a NEXRAD site on S3."""
    now = datetime.now(timezone.utc)
    # S3 bucket uses 3-letter codes without K prefix (KLIX → LIX)
    s3_site = site_id[1:] if site_id.startswith('K') and len(site_id) == 4 else site_id
    prefix = f"{s3_site}_STI_{now.strftime('%Y_%m_%d')}"

    try:
        resp = s3.list_objects_v2(
            Bucket=STI_BUCKET, Prefix=prefix, MaxKeys=50
        )
        keys = [obj['Key'] for obj in resp.get('Contents', []) if '_STI_' in obj['Key']]
        if not keys:
            # Try yesterday if early UTC
            if now.hour < 2:
                yesterday = now - timedelta(days=1)
                prefix2 = f"{s3_site}_STI_{yesterday.strftime('%Y_%m_%d')}"
                resp2 = s3.list_objects_v2(Bucket=STI_BUCKET, Prefix=prefix2, MaxKeys=50)
                keys = [obj['Key'] for obj in resp2.get('Contents', []) if '_STI_' in obj['Key']]
            if not keys:
                return None
        # Keys sort alphabetically = chronologically, take the last one
        keys.sort()
        return keys[-1]
    except Exception as e:
        log.debug(f"STI list error for {site_id}: {e}")
        return None


def get_file_age_sec(key: str) -> float:
    """Extract timestamp from STI filename and compute age."""
    # Format: KLIX_STI_2026_03_08_01_35_40
    parts = key.split('_')
    if len(parts) < 8:
        return float('inf')
    try:
        y, mo, d = int(parts[2]), int(parts[3]), int(parts[4])
        h, mi, se = int(parts[5]), int(parts[6]), int(parts[7])
        file_dt = datetime(y, mo, d, h, mi, se, tzinfo=timezone.utc)
        return (datetime.now(timezone.utc) - file_dt).total_seconds()
    except (ValueError, IndexError):
        return float('inf')


def parse_sti_file(key: str, site_id: str) -> list[dict]:
    """
    Fetch and parse a NEXRAD Level III STI file from S3.
    
    STI tabular format:
      STM  AZ/RAN  MOVEMENT   DBZM  HT   TOP  FCST MVMT
      ID  DEG/NM   DEG/KTS          KFT  KFT   DEG/NM  
      F4  242/ 67  242/ 22    53   6.3  22.4  245/ 67
    
    MOVEMENT is DIR/SPD (direction degrees / speed knots)
    """
    site = NEXRAD_SITE_MAP.get(site_id)
    if not site:
        return []

    site_lat, site_lon = site['lat'], site['lon']

    try:
        obj = s3.get_object(Bucket=STI_BUCKET, Key=key)
        data = obj['Body'].read()
    except Exception as e:
        log.debug(f"STI fetch error {key}: {e}")
        return []

    cells = []
    import re

    try:
        # Decode binary as ASCII — the Tabular Alphanumeric Block is readable text
        # embedded within the binary Level III structure
        text_data = data.decode('ascii', errors='replace')
        
        # Split on common line endings (binary data may use \r\n, \n, or \r)
        lines = re.split(r'[\r\n]+', text_data)

        for line in lines:
            line = line.strip()
            if not line or len(line) < 10:
                continue

            # Match STI cell line: ID  AZ/RAN  DIR/SPD  DBZ ...
            # Cell ID is 1-2 uppercase letters + 1 digit (A0, B1, F4, AA1, etc.)
            # AZ/RAN: azimuth(deg) / range(nm)
            # DIR/SPD: movement direction(deg) / speed(kts)  
            # DBZ: max reflectivity
            m = re.match(
                r'\s*([A-Z]{1,2}\d)\s+'                    # Cell ID
                r'(\d{1,3})\s*/\s*(\d{1,3})\s+'           # AZ / RAN
                r'(\d{1,3})\s*/\s*(\d{1,3})\s+'           # DIR / SPD (MOVEMENT)
                r'(\d{1,3})',                               # DBZM
                line
            )
            if not m:
                continue

            try:
                cell_id = m.group(1)
                azimuth = int(m.group(2))
                range_nm = int(m.group(3))
                direction = int(m.group(4))    # MOVEMENT direction in degrees
                speed_kts = int(m.group(5))    # MOVEMENT speed in knots
                max_dbz = int(m.group(6))
            except (ValueError, IndexError):
                continue

            # Sanity checks
            if azimuth > 360 or range_nm > 250 or direction > 360 or speed_kts > 150:
                continue

            # Convert range/azimuth to lat/lon
            range_km = range_nm * 1.852
            az_rad = math.radians(azimuth)
            lat = site_lat + (range_km / 111.32) * math.cos(az_rad)
            lon = site_lon + (range_km / (111.32 * math.cos(math.radians(site_lat)))) * math.sin(az_rad)

            # Parse optional echo top from remaining columns
            echo_top = None
            echo_base = None
            remaining = line[m.end():]
            nums = re.findall(r'(\d+\.?\d*)', remaining)
            if len(nums) >= 2:
                try:
                    echo_base = round(float(nums[0]) * 1000)  # kft → ft
                    echo_top = round(float(nums[1]) * 1000)
                except (ValueError, IndexError):
                    pass

            cells.append({
                'cellId':         cell_id,
                'siteId':         site_id,
                'lat':            round(lat, 3),
                'lon':            round(lon, 3),
                'motionDir':      direction,
                'motionSpeedKts': speed_kts,
                'motionSpeedMph': round(speed_kts * 1.15078),
                'maxDbz':         max_dbz,
                'vil':            None,
                'echoTop':        echo_top,
                'echoBase':       echo_base,
                'time':           datetime.now(timezone.utc).isoformat(),
            })

        if cells:
            log.info(f"  [STI] {site_id}: {len(cells)} cells from {key}")

    except Exception as e:
        log.warning(f"STI parse error for {key}: {e}")

    return cells


# ═══════════════════════════════════════════════════════════════════════════════
# POLL LOOPS
# ═══════════════════════════════════════════════════════════════════════════════

def glm_poll_loop():
    """Background thread — polls GLM S3 every POLL_INTERVAL seconds."""
    log.info("GLM poll loop started")
    while True:
        try:
            dt = datetime.now(timezone.utc)
            flashes = None
            used_bucket = None

            for bucket in GOES_BUCKETS:
                key = latest_glm_key(bucket, dt)
                if key is None:
                    log.warning(f"No GLM files found in {bucket}")
                    continue

                fname = key.split('/')[-1]
                try:
                    s_part = [p for p in fname.split('_') if p.startswith('s')][0]
                    year   = int(s_part[1:5])
                    doy    = int(s_part[5:8])
                    hour   = int(s_part[8:10])
                    minute = int(s_part[10:12])
                    second = int(s_part[12:14])
                    file_dt = datetime(year, 1, 1, hour, minute, second,
                                       tzinfo=timezone.utc) + timedelta(days=doy - 1)
                    age = (dt - file_dt).total_seconds()
                    if age > MAX_AGE_SEC:
                        log.info(f"Most recent GLM file is {age:.0f}s old — skipping")
                        continue
                except Exception:
                    file_dt = dt

                flashes = parse_glm_file(bucket, key)
                used_bucket = bucket
                break

            if flashes is not None:
                clusters = cluster_flashes(flashes)
                with _lock:
                    _state['clusters']    = clusters
                    _state['file_time']   = file_dt
                    _state['fetch_time']  = dt
                    _state['source']      = used_bucket
                    _state['file_count'] += 1
                    _state['flash_count'] += len(flashes)
                    _state['error']       = None
                log.info(f"GLM updated: {len(clusters)} clusters from {len(flashes)} flashes")
            else:
                with _lock:
                    _state['error'] = 'No recent GLM file found'

        except Exception as e:
            log.error(f"GLM poll error: {e}", exc_info=True)
            with _lock:
                _state['error'] = str(e)

        time.sleep(POLL_INTERVAL)


def sti_poll_loop():
    """Background thread — polls NEXRAD STI from S3 every STI_POLL_INTERVAL seconds."""
    log.info(f"STI poll loop started — {len(NEXRAD_SITES)} sites, every {STI_POLL_INTERVAL}s")

    while True:
        try:
            start_time = time.time()
            all_cells = []
            sites_checked = 0
            sites_with_data = 0
            errors = 0

            with _sti_lock:
                _sti_state['poll_count'] += 1

            for site in NEXRAD_SITES:
                sites_checked += 1
                try:
                    key = get_latest_sti_key(site['id'])
                    if not key:
                        continue

                    # Log first few successful key finds for debugging
                    if sites_with_data < 3:
                        log.info(f"  [STI] Found key for {site['id']}: {key}")

                    # Skip if already processed
                    with _sti_lock:
                        if _sti_state['last_file_by_site'].get(site['id']) == key:
                            existing = [c for c in _sti_state['cells'] if c['siteId'] == site['id']]
                            all_cells.extend(existing)
                            continue

                    # Check age
                    age = get_file_age_sec(key)
                    if age > STI_MAX_AGE_SEC:
                        if sites_with_data < 3:
                            log.info(f"  [STI] {site['id']} file too old ({age:.0f}s)")
                        continue

                    cells = parse_sti_file(key, site['id'])
                    if cells:
                        sites_with_data += 1
                        all_cells.extend(cells)
                        with _sti_lock:
                            _sti_state['last_file_by_site'][site['id']] = key

                except Exception as e:
                    errors += 1
                    log.debug(f"STI error for {site['id']}: {e}")

            # Also keep recent cells from sites we didn't update
            now_dt = datetime.now(timezone.utc)
            with _sti_lock:
                for cell in _sti_state['cells']:
                    key = f"{cell['siteId']}_{cell.get('cellId', '')}_{cell['lat']},{cell['lon']}"
                    existing_keys = set(
                        f"{c['siteId']}_{c.get('cellId', '')}_{c['lat']},{c['lon']}"
                        for c in all_cells
                    )
                    if key not in existing_keys:
                        try:
                            cell_age = (now_dt - datetime.fromisoformat(cell['time'])).total_seconds()
                            if cell_age < STI_MAX_AGE_SEC:
                                all_cells.append(cell)
                        except (ValueError, KeyError):
                            pass

            with _sti_lock:
                _sti_state['cells'] = all_cells
                _sti_state['last_poll'] = datetime.now(timezone.utc).isoformat()
                _sti_state['sites_checked'] = sites_checked
                _sti_state['sites_with_data'] = sites_with_data
                _sti_state['error_count'] += errors

            elapsed = time.time() - start_time
            log.info(f"STI poll #{_sti_state['poll_count']}: "
                     f"{sites_checked} sites, {sites_with_data} with data, "
                     f"{len(all_cells)} cells ({elapsed:.1f}s)")

        except Exception as e:
            log.error(f"STI poll error: {e}", exc_info=True)
            with _sti_lock:
                _sti_state['error_count'] += 1

        time.sleep(STI_POLL_INTERVAL)


# ═══════════════════════════════════════════════════════════════════════════════
# FLASK API
# ═══════════════════════════════════════════════════════════════════════════════

app = Flask(__name__)
CORS(app)


@app.route('/glm')
def glm_endpoint():
    with _lock:
        clusters   = list(_state['clusters'])
        file_time  = _state['file_time']
        fetch_time = _state['fetch_time']
        source     = _state['source']
        error      = _state['error']

    features = []
    for c in clusters:
        features.append({
            'type': 'Feature',
            'geometry': {'type': 'Point', 'coordinates': [c['lon'], c['lat']]},
            'properties': {
                'count':        c['count'],
                'area':         c['area'],
                'total_energy': c.get('total_energy', 0),
            },
        })

    return jsonify({
        'type': 'FeatureCollection',
        'features': features,
        'meta': {
            'source':      source,
            'file_time':   file_time.isoformat()  if file_time  else None,
            'fetch_time':  fetch_time.isoformat() if fetch_time else None,
            'flash_total': _state['flash_count'],
            'file_total':  _state['file_count'],
            'error':       error,
        },
    })


@app.route('/status')
def status():
    with _lock:
        s = dict(_state)
        s['clusters'] = len(s['clusters'])
        if s['file_time']:  s['file_time']  = s['file_time'].isoformat()
        if s['fetch_time']: s['fetch_time'] = s['fetch_time'].isoformat()
    return jsonify(s)


@app.route('/sti')
def sti_endpoint():
    """
    Returns current NEXRAD SCIT storm cell data as GeoJSON.
    Optional: ?bounds=south,west,north,east to filter by bounding box.
    """
    with _sti_lock:
        cells = list(_sti_state['cells'])

    # Optional bounding box filter
    bounds = request.args.get('bounds')
    if bounds:
        try:
            parts = [float(x) for x in bounds.split(',')]
            if len(parts) == 4:
                south, west, north, east = parts
                cells = [c for c in cells
                         if south <= c['lat'] <= north and west <= c['lon'] <= east]
        except (ValueError, TypeError):
            pass

    features = []
    for c in cells:
        features.append({
            'type': 'Feature',
            'geometry': {'type': 'Point', 'coordinates': [c['lon'], c['lat']]},
            'properties': {
                'cellId':         c.get('cellId'),
                'siteId':         c.get('siteId'),
                'motionDir':      c.get('motionDir'),
                'motionSpeedKts': c.get('motionSpeedKts'),
                'motionSpeedMph': c.get('motionSpeedMph'),
                'maxDbz':         c.get('maxDbz'),
                'vil':            c.get('vil'),
                'echoTop':        c.get('echoTop'),
                'echoBase':       c.get('echoBase'),
                'time':           c.get('time'),
            },
        })

    return jsonify({
        'type': 'FeatureCollection',
        'features': features,
        'meta': {
            'storm_count':    len(features),
            'total_cells':    len(_sti_state['cells']),
            'last_poll':      _sti_state.get('last_poll'),
            'poll_count':     _sti_state.get('poll_count', 0),
            'source':         'NEXRAD Level III STI (Product 58)',
        },
    })


@app.route('/sti/status')
def sti_status():
    with _sti_lock:
        return jsonify({
            'status':          'ok',
            'storm_count':     len(_sti_state['cells']),
            'last_poll':       _sti_state.get('last_poll'),
            'poll_count':      _sti_state.get('poll_count', 0),
            'error_count':     _sti_state.get('error_count', 0),
            'sites_tracked':   len(NEXRAD_SITES),
            'sites_checked':   _sti_state.get('sites_checked', 0),
            'sites_with_data': _sti_state.get('sites_with_data', 0),
            'poll_interval_s': STI_POLL_INTERVAL,
        })


@app.route('/')
def root():
    return (
        '<h2>GLM + STI Ingest Service — MWN</h2>'
        '<p><a href="/glm">/glm</a> — GeoJSON flash clusters</p>'
        '<p><a href="/status">/status</a> — GLM service health</p>'
        '<p><a href="/sti">/sti</a> — NEXRAD storm cells (SCIT)</p>'
        '<p><a href="/sti/status">/sti/status</a> — STI service health</p>'
    )


# ═══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

def start_threads():
    """Start both poll threads. Called from __main__ or gunicorn post_fork."""
    glm_thread = threading.Thread(target=glm_poll_loop, daemon=True)
    glm_thread.start()
    log.info("GLM poll thread started")

    sti_thread = threading.Thread(target=sti_poll_loop, daemon=True)
    sti_thread.start()
    log.info("STI poll thread started")


if __name__ == '__main__':
    start_threads()
    log.info(f"MWN Ingest Service starting on 0.0.0.0:{PORT}")
    log.info(f"Endpoints: /glm, /status, /sti, /sti/status")
    app.run(host='0.0.0.0', port=PORT, debug=False, use_reloader=False)
